# This workflow will do a clean installation of node dependencies,
# trigger a lighthouse run, build the dashboard, and deploy it to
# the gh-pages branch.

name: Node.js CI - Lighthouse run and github pages deploy

permissions:
  contents: write

# on:
#   schedule:
#     - cron: '10 20 * * 5'

on:
  push:
    branches:
      - main

jobs:
  lh-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Install
        run: |
          npm ci
          npm --prefix lighthouse ci
      
      - name: Lighthouse Runs and Build Dashboard
        run: |
          npm run lighthouse
          npm run build
        
      - name: Deploy Dashboard
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
