# This workflow will do a clean installation of node dependencies,
# then do a Lighthouse run.

name: Node.js CI - Complete a Lighthouse run.

# on:
#   schedule:
#     - cron: '20 0,2 * * *'

on: workflow_dispatch

jobs:
  lighthouse-run:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Install Packages
        run: |
          npm --prefix lighthouse ci
          npm ci
      
      - name: Lighthouse Run
        run: npm run lighthouse
        
      - name: Commit Lighthouse Reports
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Adding Lighthouse reports
          push_options: --force

      - name: Build Dashboard
        run: npm run build

      - name: Deploy Dashboard
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
